# Build LArRecoND against the full Pandora stack, standalone
name: Build LArRecoND

# Controls when the workflow will run
on:
  # Trigger the workflow on push to master, or any pull request.
  # workflow_dispatch allows manual running through the GitHub UI.
  push:
    branches:
      - master
  pull_request:
    branches:
      - "*"
  workflow_dispatch:

# Concurrency group ensures that only one workflow run is active for a given PR
# or branch at a time.
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

# Top level environment variables...
env:
  PRIMARY_COMPILER: gcc-13

# First workflow: Build Pandora.
#
# Each of the sub-stages in the build job run in parallel with a different
# compiler.
jobs:

  # First things first, if this is a pull request, save the PR number as an
  # artifact for later use.
  setup:
    runs-on: ubuntu-latest
    name: Save PR Info
    if: github.event_name == 'pull_request' && github.repository_owner == 'PandoraPFAOrg'
    steps:

      - name: Save PR Number
        run: |
          mkdir -p pr-info
          echo ${{ github.event.pull_request.number }} > pr-info/pr_number.txt

      - name: Upload PR Number
        uses: actions/upload-artifact@v7
        with:
          name: pr-number
          path: pr-info/

  build:
    runs-on: ubuntu-latest
    name: LArRecoND - ${{ matrix.compiler.c }}

    # Only run in the PandoraPFAOrg repos.
    if: github.repository_owner == 'PandoraPFAOrg'

    # Defines the build matrix, so what combinatorics of compiler etc. to test.
    strategy:
      fail-fast: false # Don't quit other jobs if one job fails.
      matrix:
        compiler: [{ cpp: g++-13, c: gcc-13 }, { cpp: clang++, c: clang }]

    # Set the compiler env vars to ensure the correct compiler is used.
    # Similarly, set all the URLs for external dependencies in one place.
    env:
      CC: ${{ matrix.compiler.c }}
      CXX: ${{ matrix.compiler.cpp }}
      ROOT_URL: "https://root.cern/download/root_v6.36.04.Linux-ubuntu24.04-x86_64-gcc13.3.tar.gz"
      TORCH_URL: "https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.1.1%2Bcpu.zip"

    steps:
      # Get the current repo...
      - name: Checkout LArRecoND Repository
        uses: actions/checkout@v7

      # Install required dependencies...
      - name: Setup Env
        uses: ./.github/actions/setup-env

      # Grab ROOT...
      - name: Setup External Dependencies
        uses: ./.github/actions/setup-externals
        with:
          root-url: ${{ env.ROOT_URL }}

      # Build all of Pandora!
      - name: Build Pandora Software Stack
        uses: ./.github/actions/build-pandora

      # At the end of the build, save a copy of the build env as an artifact for
      # later use in the test stage.
      - name: Archive Build Environment
        uses: actions/upload-artifact@v7
        if: matrix.compiler.c == env.PRIMARY_COMPILER
        with:
          name: pandora-build-env-${{ matrix.compiler.c }}
          path: /pandora
          retention-days: 1

  # Next, a testing workflow.
  #
  # This will take one of the just made builds and use it for a live test.
  # I.e. run over the defined datasets.
  #
  # We do this as a follow up, since it only needs to be done once,
  # and it means we don't bother doing a test if one of the build failed.
  test:
    needs: build
    runs-on: ubuntu-latest
    if: github.repository_owner == 'PandoraPFAOrg'

    # Define a matrix of datasets to test against. Each dataset has its own parameters.
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: "2x2 MiniRun6.5"
            id: two-by-two
            data_url: "https://portal.nersc.gov/project/dune/data/2x2/simulation/productions/MiniRun6.5_1E19_RHC/MiniRun6.5_1E19_RHC.flow/FLOW/0000000/MiniRun6.5_1E19_RHC.flow.0000000.FLOW.hdf5"
            geometry_url: "https://raw.githubusercontent.com/DUNE/2x2_sim/refs/heads/develop/geometry/Merged2x2MINERvA_v4/Merged2x2MINERvA_v4_withRock.gdml"
            flags: "0 0 0"
            xml: "PandoraSettings_LArRecoND_ThreeD_RockMuTagging.xml"
            run_type: "CRRemHitsSliceNu"
            events: 25
          - name: "NDLAr MicroProdN4p1"
            id: ndlar
            data_url: "https://portal.nersc.gov/project/dune/data/ND/MicroProdN4p1/run-ndlar-flow/MicroProdN4p1_NDComplex_FHC.flow.full/FLOW/0002000/MicroProdN4p1_NDComplex_FHC.flow.full.0002459.FLOW.hdf5"
            geometry_url: "https://raw.githubusercontent.com/DUNE/2x2_sim/refs/heads/develop/geometry/Merged2x2MINERvA_v4/Merged2x2MINERvA_v4_withRock.gdml"
            flags: "0 0 2"
            xml: "PandoraSettings_LArRecoND_ThreeD_CheatedSlicing_RockMuTagging.xml"
            run_type: "CRRemHitsSliceNu"
            events: 1

    name: Test ${{ matrix.name }} Data

    steps:
      # Grab the repo again...
      - name: Checkout LArRecoND Repository
        uses: actions/checkout@v7

      # And setup the environment...
      - name: Setup Env
        uses: ./.github/actions/setup-env

      # And Python (for FLOW conversion)...
      - name: Setup Python
        uses: ./.github/actions/setup-python

      # Grab the build we just made, so we can run the tests with the same
      # setup.
      - name: Download Build Environment
        uses: actions/download-artifact@v8
        with:
          name: pandora-build-env-${{ env.PRIMARY_COMPILER }}
          path: /pandora

      # Start setting up for the data...
      - name: Setup Downloads
        run: |
          mkdir -p /pandora/data

      # Generate a unique hash key for the data files, so we can cache them.
      - name: Generate URL Hash Key
        id: url-key
        shell: bash
        run: |
          hash=$(printf '%s|%s' '${{ matrix.data_url }}' '${{ matrix.geometry_url }}' | sha256sum | cut -d ' ' -f 1)
          echo "hash=$hash" >> "$GITHUB_OUTPUT"

      # Already have a cache for these files? Grab it!
      - name: Cache Data Files
        id: cache-data
        uses: actions/cache/restore@v6
        with:
          path: |
            /pandora/data/*.hdf5
            /pandora/data/*.gdml
          key: ${{ steps.url-key.outputs.hash }}

      # No cache? Download them.
      - name: Download Data Files
        id: download-data
        if: steps.cache-data.outputs.cache-hit != 'true'
        shell: bash
        run: |
          echo "Downloading data files..."
          cd /pandora/data/
          sleep $((RANDOM % 120))
          wget --show-progress --progress=bar:force:noscroll \
            --tries=5 --timeout=60 --waitretry=10 \
            "${{ matrix.data_url }}" -O input_data.hdf5
          wget --show-progress --progress=bar:force:noscroll \
            --tries=5 --timeout=60 --waitretry=10 \
            "${{ matrix.geometry_url }}" -O geometry.gdml

      # Fully process the two input files - HDF5 -> ROOT + Geo Conversion.
      - name: Process Files With Python
        shell: bash -l {0}
        env:
          UCX_TLS: tcp,self,sm
        run: |
          echo "Fixing data folder..."
          sudo chmod -R +x /pandora

          echo "Processing files with Python..."
          cd /pandora/data/
          python3 /pandora/LArRecoND/ndlarflow/h5_to_root_ndlarflow.py /pandora/data/input_data.hdf5 ${{ matrix.flags }} converted_flow.root

          echo "Setting up environment for ROOT..."
          source /pandora/setup.sh

          echo "Converting processed file to ROOT..."
          root -l -b -q /pandora/LArRecoND/ndlarflow/rootToRootConversion.C+\(true,\"converted_flow.root\",\"processed_output.root\"\)
          ln -s processed_output.root /pandora/data/LArRecoNDInput.root

          echo "Converting geometry GDML to ROOT..."
          root -l -b <<EOF
            TGeoManager::LockDefaultUnits(kFALSE);
            TGeoManager::SetDefaultUnits(TGeoManager::kRootUnits);
            TGeoManager::Import("/pandora/data/geometry.gdml");
            gGeoManager->Export("/pandora/data/geometry.root");
          EOF

          echo "Data processing complete."
          ls -lh /pandora/data/

      # Finally, run Pandora with the processed input data and geometry, using
      # the specified XML settings.
      - name: Run Binary Tests
        id: binary
        run: |
          source /pandora/setup.sh
          cd /pandora/data/
          /pandora/LArRecoND/build/PandoraInterface \
           -i /pandora/LArRecoND/settings/${{ matrix.xml }} \
           -r ${{ matrix.run_type }} \
           -e /pandora/data/processed_output.root \
           -g /pandora/data/geometry.root \
           -f SPMC \
           -n ${{ matrix.events }} -N

      # If this is a pull request, download the reference ROOT file for validation.
      #
      # This should be the latest successful output from the master branch, so
      # we can compare the current PR output against it.
      - name: Download Reference File
        if: github.event_name == 'pull_request'
        uses: dawidd6/action-download-artifact@v3
        with:
          name: reco-validation-${{ matrix.id }}
          path: /pandora/data/reference
          branch: master
          if_no_artifact_found: warn

      # After this, validate the output in a basic way: Check the output exists,
      # has entries and make some basic plots. Also include comparisons, if
      # possible.
      - name: Validate and Upload Reconstruction Results
        if: always()
        uses: ./.github/actions/validate-reconstruction
        with:
          dataset-id: ${{ matrix.id }}
          dataset-name: ${{ matrix.name }}
          binary-outcome: ${{ steps.binary.outcome }}
          job-outcome: ${{ job.status }}
          is-pull-request: ${{ github.event_name == 'pull_request' }}
          reference-file: /pandora/data/reference/${{ matrix.id }}-LArRecoND.root

      # Next, if we did download the data, cache it for the next run.
      - name: Save Data Cache
        uses: actions/cache/save@v6
        if: always() && steps.download-data.outcome == 'success'
        with:
          path: |
            /pandora/data/*.hdf5
            /pandora/data/*.gdml
          key: ${{ steps.url-key.outputs.hash }}
